name: Unit Test - Python

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependency-group:
          - {name: dev,  make-target: test-python-dev}
          - {name: prod, make-target: test-python}

    name: Test ${{ matrix.dependency-group.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Verify
        run: make verify

      - name: Run Tests
        run: |
          make ${{ matrix.dependency-group.make-target }} report=xml

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Pass the GITHUB_TOKEN
          flag-name: ${{ matrix.dependency-group.name }}
